version: '3.8'

services:
  traefik:
    image: traefik:v3.6.9
    command:
      - '--api.insecure=true'
      - '--providers.file.filename=/etc/traefik/dynamic.yml'
      - '--entrypoints.web.address=:5173'
    ports:
      - '5173:5173'
      - '8080:8080'
    volumes:
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml
