buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.install]
cmds = ["npm install -g pnpm@10.33.0", "node -v", "pnpm install --frozen-lockfile --config.engine-strict=false"]

[phases.build]
cmds = ["pnpm --config.engine-strict=false build"]

[start]
cmd = "node build"
